name: google-chat-desktop
version: 3.3.0
summary: Google Chat Desktop
description: |
  An unofficial desktop app for Google Chat.

  This is a desktop app for Google Chat https://chat.google.com/, a chatbot that uses Generative AI to have conversations with you.

  Build based on https://github.com/zviryatko/google-chat-electron repository.
base: core22
build-snaps:
  - gnome-42-2204/latest/candidate
confinement: strict
grade: stable
architectures:
  - amd64

apps:
  google-chat-desktop:
    command: "google-chat-desktop --no-sandbox"
    extensions: [gnome]
    desktop: meta/gui/google-chat-desktop.desktop
    plugs:
      - desktop
      - desktop-legacy
      - audio-playback
      - home
      - removable-media
      - browser-support
      - network
      - network-bind
      - network-observe
      - unity7
      - u2f-devices
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  libappindicator:
    plugin: nil
    stage-packages:
      - libappindicator3-1
    prime:
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdbusmenu*.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libappindicator*.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libindicator*.so*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgtk*.so*

  google-chat-desktop:
    after: [ libappindicator ]
    plugin: nil
    source: https://github.com/zviryatko/google-chat-electron.git
    source-tag: 3.2.0
    override-build: |
      # workaround for build.snapcraft.io builds
      # https://bugs.launchpad.net/bugs/1886861
      # if [ -n "$http_proxy" ]; then
      #   export ELECTRON_GET_USE_PROXY=1
      #   export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
      #   export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      # fi
      npm install
      npm run pack:linux
      cp -rv ./dist/google-chat-electron-linux-x64/* $CRAFT_PRIME
      mv $CRAFT_PRIME/google-chat-electron $CRAFT_PRIME/google-chat-desktop
      mkdir -p $CRAFT_PRIME/meta/gui
      echo -e "[Desktop Entry]\nName=Google Chat\nX-GNOME-FullName=Google Chat\nComment=Google Chat Desktop\nCategories=GNOME;Utility;\nExec=google-chat-desktop\nIcon=\${SNAP}/meta/gui/google-chat-desktop.svg\nTerminal=false\nType=Application\nVersion=1.0.0" > $CRAFT_PRIME/meta/gui/google-chat-desktop.desktop
      cp resources/icons/normal/scalable.svg $CRAFT_PRIME/meta/gui/google-chat-desktop.svg
    build-snaps:
      - node/23/stable
    build-packages:
      - unzip
    stage-packages:
      - libnss3
      - libnspr4
      - libc6
